### PR TITLE
Version 2.8.1

### PR DESCRIPTION
**Pull request by ddruker**
Update to version 2.8.1

### CODE REVIEW

**Review by Krisztiaan — APPROVED** [review]

**Review by sudharshan-kustomer — APPROVED** [review]

**Comment by zilberas** [comment]
Guys, I'm getting this error everytime I try to log smth in debugger (david had hardcoded smth). I reported this couple of months ago. Release  2.8.1 still has the isssue.

We now have to hard code 2.7.8 version (SPM), since it's newest that is working.

Screenshot 2023-08-24 at 14 44 54

**Comment by zilberas** [comment]
! URGENT !
Guys, we can not use/prepare the upcoming iOS release (15.0), because your SDK do not support upcoming tools (Xcode 15.0, swift)


The static part of your "kustomer-ios" package (specifically, KustomerChat.xcframework) MUST be built with a `BUILD_LIBRARIES_FOR_DISTRIBUTION=YES` flag. This will allow it to be compatible with upcoming versions of swift (Library evolution support, ABI stability)
https://www.swift.org/blog/library-evolution/

Please fix the issue as soon as possible. 
If you don't, the will HAVE TO DISABLE customer support features in our product to be able to release our iOS app.


If you need any further tachnical assistance from - please ask, our devs will be happy to help.
@ddruker @Krisztiaan @sudharshan-kustomer 

Screenshot 2023-08-30 at 20 16 29

**Comment by Krisztiaan** [comment]
@zilberas We have been looking into your report since your first report quite a lot the past couple weeks, and it has been quite a lot of investigation into how our SDK interacts with it's dependency, and the app. At this point we are not yet able to come up with a good enough solution to this problem, due to it's somewhat third-party related nature, but we're working with them on the resolution.

We just recently got to a point where this issue can be resolved in Cocoapods, and are in the process of figuring out the SPM release.

As for your suggestions, thank you, the problem is, both the distribution and the evolution flags are set, but since we're building a binary archive, there are cross-SDK linking issues and limitations in swift that we need to work around for SPM to be able to link.

The error message you are seeing is unfortunately not entirely truthful to the underlying issue.

We also can't risk releasing a production build with a beta toolchain that would maybe fix this issue for a few weeks or a month until a new Xcode 15 beta build is out.

We are grateful for your patience on the Xcode beta support, and hope this message indicates that we do in fact see, and want to see the end of this issue just as much as you (I'm using Xcode 15 as well, and am using our Cocoapods workaround for our React Native SDK).

**Comment by zilberas** [comment]
@Krisztiaan Thank you for the explanation - we're very happy to hear that this is under investigation on your side.
Nevertheless, I tried to integrate `KustomerChat` into our project using `cocoapods` - IT DOES NOT WORK.

Guys, you don't have to release "a production build with a beta toolchain" - just make that build as a separate "beta_xcode15" branch, so we can point to it. We can't do it ourselves. We can't fork & fix the framework, because it is statically built by you, guys.

Now, we completely de-integrated Kustomer (and probably will be releasing a version without CS features), because we HAVE to keep developing features promised to Apple, and we HAVE to be able to compile our product with beta toolchain.

Screenshot 2023-09-04 at 10 16 04
Screenshot 2023-09-04 at 10 15 46

**Comment by Krisztiaan** [comment]
@zilberas sorry about that, Cocoapods is non-trivial as well. If you want to give it another shot, see the gist below.

If you're not using `use_frameworks!`, then due to build type + linking limitations, you'd have to add an override to your `Podfile`. See a sample [here](https://gist.github.com/Krisztiaan/287ebd16b9c19798b0cf862f935922f2), for the two sections between the `ADD THIS` comments.

We understand this is an awful experience for the affected, and our aim is to solve it "properly", as it should also take care of the beta compatibility, without us having to maintain a pre-release version.

**Comment by zilberas** [comment]
@Krisztiaan We ARE using `use_frameworks!` 
I tried to add & execute `pod_fix(pre_install)` - still the same error.

Screenshot 2023-09-05 at 11 13 09

**Comment by zilberas** [comment]
Hello again.
Official iOS 17 release is September 18th. So in 5 days. As you might know, in order to get the apps ready on AppStore by a specific date, you have to upload the builds in advance. (Review process, etc.)

So, WE MUST UPLOAD our build today/tomorrow in order to meet promises our company made to Apple regarding iOS17 release.

URGENT! 
Can we expect that you will provide a working any time soon?
Xcode Release Candidate is already OFFICIALLY available since yesterday, but I see no updates here in your source control, sadly.

**Pull request merged**
