### PR TITLE
Version 2.7.9

### PR DESCRIPTION
**Pull request by KevinTMiller**
Update to version 2.7.9

### CODE REVIEW

**Review by aefritz19 — APPROVED** [review]
lgtm ... heh

**Comment by zilberas** [comment]
Hey. This last release broke debugging functionality for all our project. 
We integrate Kustomer using SPM. But now any try to use debugger throws this error:
```
error: expression failed to parse:
error: stat cache file '/Users/kevintmiller/Library/Developer/Xcode/DerivedData/SDKStatCaches.noindex/iphonesimulator16.4-20238-sdkstatcache'
not found
```

Looks like kevintmiller hardoded smth here

Screenshot 2023-05-29 at 15 59 36

**Comment by ddruker** [comment]
> Hey. This last release broke debugging functionality for all our project. We integrate Kustomer using SPM. But now any try to use debugger throws this error:
> 
> ```
> error: expression failed to parse:
> error: stat cache file '/Users/kevintmiller/Library/Developer/Xcode/DerivedData/SDKStatCaches.noindex/iphonesimulator16.4-20238-sdkstatcache'
> not found
> ```
> 
> Looks like kevintmiller hardoded smth here
> 
> Screenshot 2023-05-29 at 15 59 36

@zilberas Are you experiencing the issue after upgrading to v2.8.0?

**Comment by ddruker** [comment]
> Hey. This last release broke debugging functionality for all our project. We integrate Kustomer using SPM. But now any try to use debugger throws this error:
> 
> ```
> error: expression failed to parse:
> error: stat cache file '/Users/kevintmiller/Library/Developer/Xcode/DerivedData/SDKStatCaches.noindex/iphonesimulator16.4-20238-sdkstatcache'
> not found
> ```
> 
> Looks like kevintmiller hardoded smth here
> 
> Screenshot 2023-05-29 at 15 59 36

@zilberas a workaround for now is to use the `fr v` command, while we work on a fix. More information about that here.

https://lldb.llvm.org/use/map.html#examining-variables

**Comment by zilberas** [comment]
@ddruker The problem is still there with 2.8.1.
Screenshot 2023-08-24 at 14 44 54

**Comment by ddruker** [comment]
@zilberas There seems to be an issue with the lldb debugger when using macOS Ventura 13.3.1. Are you on that version? Please upgrade to the latest stable Ventura version if needed.

**Comment by zilberas** [comment]
@ddruker No, I'm on the latest 13.4.1 (c) (22F770820d)

But I can't see how macOS can be an issue. I don't understand the details, but I believe there should not be **any** hardcoded user paths inside the SDK. Something is off when specifying compiler flags or smth.

**Pull request merged**
